name: cmake-build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
        - os: macos-15
        - os: windows-2025
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install 7-zip
      uses: milliewalky/setup-7-zip@v2
    
    - name: Create Build Environment
      env:
        IDASDK_SECRET: ${{ secrets.IDASDK_SECRET }}
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        mkdir -p "${{ runner.workspace }}/build" \
              ida/idasdk
        mv binexport/ida/idasdk/idasdk*.gpg \
           ida/idasdk/
        chmod +xxx "${{ github.workspace }}/binexport/.github/scripts/decrypt_secret.sh"
        "${{ github.workspace }}/binexport/.github/scripts/decrypt_secret.sh"
        7z x -t7z  "${{ runner.workspace }}/build/idasdk91.7z" -o"${{ runner.workspace }}/build/"
    - name: Enable Developer Command Prompt (Windows)
      if: matrix.os == 'windows-2025'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Enable mold linker (Linux)
      if: matrix.os == 'ubuntu-24.04'
      uses: rui314/setup-mold@v1

    - name: Setup CMake and Ninja
      uses: lukka/get-cmake@v4.0.2
      with:
        cmakeVersion: 4.0.2
        ninjaVersion: 1.12.1

    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        cmake "${{ github.workspace }}" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DIdaSdk_ROOT_DIR=${{ runner.workspace }}/build/idasdk91"

    - name: Build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: Test
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: ctest --build-config "${BUILD_TYPE}" --output-on-failure -R '^[A-Z]'

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BinExport-${{ runner.os }}
        path: |
          ${{ runner.workspace }}/build/binaryninja/binexport*
          ${{ runner.workspace }}/build/ida/binexport*
          ${{ runner.workspace }}/build/tools/binexport2dump*
